### ISSUE TITLE
About the hand-crafted cases

### ISSUE THREAD

**Issue by PhilWallace** [ai4cloudops/SecLLMHolmes#1]
Thanks for the great work!

I have a question about how then ''hand-crafted'' examples are made. For example:
https://github.com/ai4cloudops/SecLLMHolmes/tree/main/datasets/hand-crafted/dataset/CWE-476

Are these cases from real-world project? Or these vulnerable codes are crafted from scratch?

Many thanks

**Comment by saadullah01** [comment]
Hi, 

Our "hand-crafted" code scenarios are crafted from scratch and each one of them is meticulously designed to assess specific capabilities of LLMs.

Saad
