### ISSUE TITLE
Inconsistent results in paper and published file

### ISSUE THREAD

**Issue by Leeziao** [ai4cloudops/SecLLMHolmes#4]
In our-results/real-world/gpt-4.json:
![image](https://github.com/ai4cloudops/SecLLMHolmes/assets/77946096/eb181bd8-9aa2-4ccc-a5b8-e4e3cf4bfc98)

The `pred` field equals `yes`, indicating that the evaluated LLM (here gpt-4) believes the tested code **has** a vulnerability. While the tested code is from the patched version, the ground truth should be it is **non-vulnerable**. Therefore gpt-4 wrongly predicts this case.

![image](https://github.com/ai4cloudops/SecLLMHolmes/assets/77946096/1a464f1a-b820-446c-bbcd-fa89980944d3)

This case is marked as a green tick in the published paper, which means gpt-4 correctly predicts it.

I wonder why there is such an inconsistency.

**Comment by saadullah01** [comment]
Hi,

Thank you very much for pointing this out, I found a bug in my evaluation code which caused this inconsistency. I have fixed it and updated the paper on Arxiv. Moreover, we are in the process of updating the version in IEEE S&P Journal.

Thank you!
